<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Todo;
use App\Models\User;
use Carbon\Carbon;

class TodoSeeder extends Seeder
{
    public function run(): void
    {
        $users = User::pluck('id')->toArray();

        $titles = [
            'Follow up with client – Dhaka Branch',
            'Prepare proposal draft for ABC Ltd.',
            'Update CRM pipeline for new leads',
            'Team meeting – Q4 strategy planning',
            'Check pending invoice payment – Client XYZ',
            'Finalize sales contract – Sylhet Branch',
            'Review project milestones – ERP Integration',
            'Send campaign performance report',
            'Client onboarding session',
            'Prepare quotation for tender submission',
            'Update product pricing in CRM',
            'Schedule demo with potential client',
            'Prepare presentation for board meeting',
            'Review overdue tasks in Sales Department',
            'Plan marketing campaign for New Year 2026',
            'Coordinate with supplier for delivery',
            'Update system user permissions',
            'Review pipeline conversion rates',
            'Organize weekly team sync',
            'Finalize estimation for project Alpha'
        ];

        $categories = ['Sales', 'Marketing', 'Finance', 'Projects', 'Support'];

        $statusOptions = [
            1 => 'Pending',
            2 => 'In Progress',
            3 => 'Completed',
            4 => 'On Hold'
        ];

        $priorityOptions = [
            1 => 'High',
            2 => 'Medium',
            3 => 'Low'
        ];

        $startDate = Carbon::create(2025, 9, 8);
        $endDate   = Carbon::create(2026, 2, 2);

        foreach (range(0, 19) as $i) {
            $dueDate = Carbon::createFromTimestamp(rand($startDate->timestamp, $endDate->timestamp));

            Todo::create([
                'title' => $titles[$i],
                'priority' => array_rand($priorityOptions),
                'status' => array_rand($statusOptions),
                'due_date' => $dueDate,
                'category' => $categories[array_rand($categories)],
                'assigned_to' => $users ? $users[array_rand($users)] : null,
                'description' => 'This task relates to ' . strtolower($categories[array_rand($categories)]) . ' operations. Generated by seeder for testing CRM workflows.',
            ]);
        }
    }
}
